"""add index to post timestamp

Revision ID: 580ac08dc107
Revises: ec34b9547457
Create Date: 2026-08-29 16:31:01.017857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580ac08dc107'
down_revision = 'ec34b9547457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_timestamp'))

    # ### end Alembic commands ###
